name: Deploy Pipeline

on:
  push:
    branches:
      - master

jobs:
  create-s3-bucket:
    name: Create S3 Bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Terraform setup
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      # AWS credentials setup
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Apply Terraform to create S3 bucket
      - name: Apply Terraform
        run: terraform apply -target=aws_s3_bucket.terraform_bucket -auto-approve

  configure-backend:
    name: Configure Backend
    runs-on: ubuntu-latest
    needs: create-s3-bucket
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Terraform setup
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      # AWS credentials setup
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # Initialize Terraform with backend configuration
      - name: Initialize Terraform
        run: terraform init

      # Apply Terraform
      - name: Apply Terraform
        run: terraform apply -auto-approve
